Remove multiprocessing-related coverage files

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,4 +27,9 @@ after_success:
     # Ignore codecov failures because we don't want travis to report a
     # failure in the github UI just because the coverage report failed
     # to be published.
-    - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "failed"; fi
+    - |
+      if [[ "$COVERAGE" == "true" ]]; then
+        ls -ltr .coverage.*
+        rm -rf .coverage.*
+        codecov || echo "failed"
+      fi
